import os
import heapq
from typing import List


def external_sort(file_path: str, output_file: str, chunk_size: int) -> None:

    def read_chunk(file, chunk_size):
            chunk = []
                    for _ in range(chunk_size):
                                line = file.readline()
                                            if not line:
                                                            break
                                                                        chunk.append(int(line.strip()))
                                                                                return chunk

                                                                                    def write_chunk(chunk, temp_file):
                                                                                            with open(temp_file, 'w') as f:
                                                                                                        for num in chunk:
                                                                                                                        f.write(f"{num}\n")

                                                                                                                            def merge_files(temp_files, output_file):
                                                                                                                                    open_files = [open(temp_file, 'r') for temp_file in temp_files]
                                                                                                                                            current_lines = [file.readline().strip() for file in open_files]

                                                                                                                                                    with open(output_file, 'w') as output:
                                                                                                                                                                while any(current_lines):
                                                                                                                                                                                min_index = min(
                                                                                                                                                                                                    (i for i in range(len(current_lines)) if current_lines[i] != ""),
                                                                                                                                                                                                                        key=lambda i: int(current_lines[i])
                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                        output.write(f"{current_lines[min_index]}\n")

                                                                                                                                                                                                                                                                        next_line = open_files[min_index].readline().strip()
                                                                                                                                                                                                                                                                                        current_lines[min_index] = next_line if next_line else ""
                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                for file in open_files:
                                                                                                                                                                                                                                                                                                                            file.close()


                                                                                                                                                                                                                                                                                                                                temp_files = []
                                                                                                                                                                                                                                                                                                                                    with open(file_path, 'r') as input_file:
                                                                                                                                                                                                                                                                                                                                            chunk_index = 0
                                                                                                                                                                                                                                                                                                                                                    while True:
                                                                                                                                                                                                                                                                                                                                                                chunk = read_chunk(input_file, chunk_size)
                                                                                                                                                                                                                                                                                                                                                                            if not chunk:
                                                                                                                                                                                                                                                                                                                                                                                            break
                                                                                                                                                                                                                                                                                                                                                                                                        chunk.sort()
                                                                                                                                                                                                                                                                                                                                                                                                                    temp_file = f"temp_chunk_{chunk_index}.txt"
                                                                                                                                                                                                                                                                                                                                                                                                                                write_chunk(chunk, temp_file)
                                                                                                                                                                                                                                                                                                                                                                                                                                            temp_files.append(temp_file)
                                                                                                                                                                                                                                                                                                                                                                                                                                                        chunk_index += 1

                                                                                                                                                                                                                                                                                                                                                                                                                                                            merge_files(temp_files, output_file)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                # for temp_file in temp_files:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    #     os.remove(temp_file)


                                                                                                                                                                                                                                                                                                                                                                                                                                                                    input_file = "input_to_sort.txt"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    output_file = "sorted_output.txt"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    chunk_size = 300

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    external_sort(input_file, output_file, chunk_size)